# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01a1dd8423202a4014c3a23169f42041859fe48e12355ca453b0021259f5e8aa6618c876f9c95d878773b859b5d092d7487a974040b34deabb5046b74f3233c6

test:
  secret_key_base: 8cd9d08c569f131c190bc9cad5246b41529c07ad3ef31907fded1e0a4a94bfd64e212c513c0ff54be420ff5066e0ec088a5ec0bfb210bdde67902acce55e4b22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
